name: metrics-app-cs-plugin
description: Plugin para configurar métricas em seu projeto projeto, onde abstraímos toda complexidade deste processo de codificação, trazendo para seu projeto simplicidade para garantir o uso de métricas, sejam elas de negócio, infraestutura ou monitoramento.
types:
  - app
inputs:
  - label: Set Type
    type: text
    default: "Prometheus"
    name: type
    items:
      - "Prometheus"

displayName: Metrics - Plugin

picture: "plugin.png"

category: backend, observability

compatibility:
  - net5.0
  - net6.0

about: about.md

usage: usage.md

useCase: useCase.md

implementation: implementation.md

technologies: [".NET", "C#", "Prometheus"]