name: metrics-app-cs-plugin
description: Plugin para configurar métricas em seu projeto projeto.
types:
  - app
inputs:
  - label: Set Type
    type: text
    default: "Prometheus"
    name: type
    items:
      - "Prometheus"

hooks:
#package
  - type: run
    trigger: before-render
    commands:
      - dotnet add src/{{global_inputs.project_name}}.Application package StackSpot.Metrics
      - dotnet add src/{{global_inputs.project_name}}.Infrastructure package StackSpot.Metrics
#dependencyinjection
  - type: edit
    trigger: before-render
    path: "src/{{project_name}}.Application/Common/StackSpot/DependencyInjection.cs"
    changes:
      - search:
          string: "using"
          insert-before:
            snippet: snippets/src/Application/using.txt
          when:
            not-exists: "using StackSpot.Metrics;"    
      - search:
          string: "return services"
          insert-before:
            snippet: snippets/src/Application/services.txt
          when:
            not-exists: "services.ConfigureMetrics();"
      - search:
          string: "return app"
          insert-before:
            snippet: snippets/src/Application/app.txt
          when:
            not-exists: "app.UseMetricServer();"              
#format
  - type: run
    trigger: after-render
    working-dir: src/{{project_name}}.Application
    commands:
      -  dotnet dotnet-format --include-generated

displayName: Metrics

picture: "plugin.png"

category: backend, observability

compatibility:
  - net5.0
  - net6.0

about: about.md

usage: usage.md

useCase: useCase.md

implementation: implementation.md

technologies: [".NET", "C#", "Prometheus"]